learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""learning_logsのURLパターンの定義"""

from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'learning_logs'
urlpatterns = [
    #ホームページ
    path('', views.index, name='index'),
    # すべてのトピックを表示するページ
    path('topics/', views.topics, name = 'topics'),
    # 全ての記事を表示するページ
    path('topics/entries/', views.entries, name='entries'),
    # 全てのユーザーを表示する
    path('users/', views.users, name='users'),
    # 個別トピックの詳細ページ
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 個別記事の詳細ページ
    path('topics/entries/<int:entry_id>/', views.entry, name='entry'),
    # 新規トピックの追加ページ
    path('new_topic/', views.new_topic, name='new_topic'),
    # 新規記事の追加ページ
    path('new_entry/', views.new_entry, name='new_entry'),
    # 記事の編集ページ
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # マイページ
    path('my_page/<int:user_id>/', views.my_page, name='my_page'),
    # 他人のページ
    path('other_users_page/<str:applicant_id>/', views.other_page, name='other_page'),
    # 他人ページ2
    path('other_users_page/other/<str:applicant_id>/', views.other_page2, name='other_page2'),
    # プロフィール設定ページ
    path('my_page/<int:user_id>/edit_profile/', views.edit_Profile, name='edit_Profile'),
    # 応募確認ページ
    path('topics/entries/<int:entry_id>/apply/<int:user_id>/', views.apply_entry, name='apply_entry'),
    # 応募完了ページ
    path('topics/entries/<int:entry_id>/apply/<int:user_id>/check/', views.apply_entered, name='apply_entered'),
    # 会社側おススメページ
    path('other_users_page/recommend/<str:profile_user>/', views.recommend, name='recommend'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""users用URLパターンの定義"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    #デフォルトの認証URLを取り込む
    path('', include('django.contrib.auth.urls')),
    # ユーザー登録ページ
    path('register/', views.register, name='register'),
]

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from socket import fromshare
from django import forms
from datetime import datetime

from .models import Topic, Entry, Profile, Apply, Recommend
# , UploadImage

class ApplyForm(forms.ModelForm):
    """応募時履歴書&自己PR追加フォーム"""
    class Meta:
        model = Apply
        fields = ['PRtext','resume']
        labels = {'PRtext':'自己PR文','resume':'履歴書をアップロードする'}
        widgets = {'PRtext': forms.Textarea(attrs={'class': 'form-control'})}

class RecommendForm(forms.ModelForm):
    """会社からの記事のおススメ"""
    # entry = forms.ModelChoiceField(queryset=Entry.objects.filter(owner=))
    class Meta:
        model = Recommend
        fields = ['entry','text']
        labels = {'entry':'おすすめする記事を選択','text':'PR文'}
        widgets = {
            'text': forms.Textarea({'class':'form-control'}),
        }

class TopicForm(forms.ModelForm):
    """新規トピック追加用フォーム"""
    class Meta:
        model = Topic
        fields = {'text'}
        labels = {'text': ''}
        widgets = {
            'text': forms.TextInput(attrs={'class': 'form-control'}),
        }

class EntryForm(forms.ModelForm):
    """新規記事追加用フォーム"""
    topic = forms.ModelChoiceField(queryset=Topic.objects.all())
    class Meta:
        model = Entry
        fields = Entryfields = ['topic','title','address','eligibility','image','text','selection_method']
        labels = {'topic': '','title': 'タイトル','address':'事業所住所','eligibility':'希望する人','image':'画像を追加','text':'本文追加','selection_method':'選考方法'}
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'eligibility': forms.Textarea(attrs={'class': 'form-control'}),
            'text': forms.Textarea({'class':'form-control'}),
            'selection_method': forms.Textarea({'class':'form-control'}),
        }

class ProfileForm(forms.ModelForm):
    """ユーザープロフィール設定フォーム"""
    class Meta:
        current_year = datetime.now().year
        min_year = current_year - 100
        model = Profile
        fields = ['family_name','first_name','sex','birthday','email','postal_code','prefectures','address','career','introduce']
        labels = {'family_name':'姓','first_name':'名前','sex':'性別','birthday':'生年月日','email':'emailアドレス','postal_code':'郵便番号', 'prefuctures':'都道府県', 'address':'都道府県以降の住所', 'career': '以前所属していた企業・役職', 'introduce':'自己PR'}
        widgets = {
            'family_name': forms.TextInput({'class':'form-control'}),
            'first_name': forms.TextInput({'class':'form-control'}),
            'email': forms.TextInput({'class':'form-control'}),
            'postal_code': forms.TextInput({'class':'form-control'}),
            'address': forms.TextInput({'class':'form-control'}),
            'career': forms.TextInput({'class':'form-control'}),
            'introduce': forms.Textarea({'class':'form-control'}),
            
            'birthday':forms.SelectDateWidget(years=[x for x in range(min_year, current_year)]),
            }

class SearchForm(forms.Form):
    keyword = forms.CharField(label='', max_length=50)
    class Meta:
        fields = ['keyword']
        labels = {'keyword':''}
        widgets = {
            'keyword': forms.TextInput(attrs={'class': 'form-control'}),
        }

learning_logs/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry, Apply, Profile, User, Recommend
from .forms import TopicForm, EntryForm, ProfileForm, SearchForm, ApplyForm, RecommendForm

# Create your views here.
def index(request):
    """学習ノートのホームページ"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """全てのトピックを表示する"""
    # topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    # objectsは全てのデータを指している→filterでuser選別
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """1つのトピックとそれについての全ての記事を表示"""
    topic = Topic.objects.get(id=topic_id)
    form = SearchForm(request.GET)
    if form.is_valid():
        keyword = form.cleaned_data['keyword']
        entries = Entry.objects.filter(text__icontains = keyword).order_by('date_added').reverse
    else:
        form = SearchForm()
        entries = Entry.objects.order_by('date_added').reverse()
        
    context = {'topic': topic,'entries': entries, 'form': form}
    return render(request, 'learning_logs/entries.html', context)
    # topic = Topic.objects.get(id=topic_id)
    # # トピックが現在のユーザーが所持するものであることを確認する
    # # if topic.owner != request.user:
    # #     raise Http404

    # entries = topic.entry_set.order_by('-date_added')
    # context = {'topic': topic, 'entries': entries}
    # return render(request, 'learning_logs/topic.html', context)


@login_required
def entries(request):
    """全ての記事を表示する"""
    #仮実装 エラー出るので要改良→ルックアップでできた
    form = SearchForm(request.GET)
    if form.is_valid():
        keyword = form.cleaned_data['keyword']
        entries = Entry.objects.filter(text__icontains = keyword).order_by('date_added').reverse
    else:
        form = SearchForm()
        entries = Entry.objects.order_by('date_added').reverse()
        
    context = {'entries': entries, 'form': form}
    return render(request, 'learning_logs/entries.html', context)


@login_required
def users(request):
    """全てのユーザーを表示する"""
    form = SearchForm(request.GET)
    if form.is_valid():
        keyword = form.cleaned_data['keyword']
        users = Profile.objects.filter(introduce__icontains = keyword)
    else:
        form = SearchForm()
        users = Profile.objects.all()
        
    context = {'users': users, 'form': form}
    return render(request, 'learning_logs/users.html', context)
    # users = Profile.objects.all()
    # context = {'users':users}
    # return render(request, 'learning_logs/users.html', context)


@login_required
def entry(request, entry_id):
    """各記事の詳細ページ_topics/entry/<entry_id>で続ける"""
    entry = Entry.objects.get(id=entry_id)
    
    # entry = Entry.object.order_by('date_added')
    context = {'entry': entry}
    return render(request, 'learning_logs/every_entry.html', context)


@login_required
def new_topic(request):
    """新規トピックを追加する"""
    if request.method != 'POST':
        #データは送信されていないので空のフォームを生成する
        form = TopicForm()

    else:
        # POSTでデータが送信されたのでこれを処理する
        form = TopicForm(data=request.POST)
        if form.is_valid():
            # 新しく追加したトピックを現在のユーザーと紐づける
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # form.save()
            return redirect('learning_logs:new_entry')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def edit_Profile(request, user_id):
    """プロフィール初期設定"""
    profile = Profile.objects.get(id=user_id)

    if request.method != 'POST':
        form = ProfileForm(instance=profile)
    
    else:
        #送信されたデータの処理
        form = ProfileForm(data=request.POST)
        if form.is_valid():
            new_profile = form.save(commit=False)
            new_profile.user = request.user
            new_profile.save()
            return redirect('learning_logs:my_page',user_id)
    
    context = {'form': form}
    return render(request, 'learning_logs/edit_profile.html', context)


@login_required
def new_entry(request):
    """新規記事を追加する"""
    # topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # データは送信されなかったので空のフォームを生成する
        form = EntryForm()
        # image_form = UploadForm()

    else:
        # POSTでデータが送信されたのでこれを処理する
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.entry_owner = request.user
            new_entry.save()
            
            return redirect('learning_logs:entries')

    # 空または無効のフォームを送信する
    context = {'form': form}
    return render(request, 'learning_logs/new_entry.html', context)



@login_required
def edit_entry(request, entry_id):
    """既存の記事を編集する"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # ログイン制限かけるやつ
    # if topic.owner != request.user:
    #     raise Http404

    if request.method != 'POST':
        # 初回リクエスト時は現在の記事の内容がフォームに埋め込まれている
        form = EntryForm(instance=entry)

    else:
        # POSTでデータが送信されたのでこれを処理する
        form = EntryForm(request.POST,request.FILES,instance=entry)
        if form.is_valid():
            # form.save()
            new_entry = form.save(commit=False)
            new_entry.save()
            return redirect('learning_logs:entry',entry_id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def edit_Profile(request, user_id):
    """プロフィール初期設定"""
    
    if Profile.objects.filter(user=user_id).exists():
        profile = Profile.objects.get(user=user_id)
        print('え')

    if request.method != 'POST':
        if Profile.objects.filter(user=user_id).exists():
            form = ProfileForm(instance=profile)
            print('あ')
        else:
            form = ProfileForm()
            print('い')
    
    else:
        #送信されたデータの処理
        if Profile.objects.filter(user=user_id).exists():
            form = ProfileForm(data=request.POST, instance=profile)
        else:
            form = ProfileForm(data=request.POST)
        if form.is_valid():
            new_profile = form.save(commit=False)
            new_profile.user = request.user
            new_profile.save()
            return redirect('learning_logs:my_page',user_id)
    
    context = {'form': form}
    return render(request, 'learning_logs/edit_profile.html', context)


@login_required
def my_page(request, user_id):
    """マイページ生成"""
    # user_id = request.user.id
    entries = Entry.objects.filter(entry_owner=request.user).order_by('-date_added')
    applys = Apply.objects.filter(owner_id=user_id)
    entry_applied = Apply.objects.filter(applicant_id=user_id)
    if Profile.objects.filter(user=user_id).exists():
        profile = Profile.objects.get(user=user_id)
    else:
        profile = ''
    recommend = Recommend.objects.filter(user=user_id)

    context = {'user_id': user_id, 'entries': entries, 'applys':applys, 'entry_applied':entry_applied, 'profile':profile, 'recommend':recommend}
    return render(request, 'learning_logs/my_page.html', context)


@login_required
def other_page(request, applicant_id):
    """他ユーザーの情報を閲覧できるページ"""
    s_id = applicant_id
    user = User.objects.get(username=s_id)
    # この方法しか今のとこ無理だけどusername重複した場合は？→重複しなかった(アカウント登録画面で弾かれた)
    profile = Profile.objects.get(user=user.id)
    # apply = Apply.objects.get(id=apply_id)
    context = {'profile':profile}

    return render(request, 'learning_logs/other_users_page.html', context)


@login_required
def other_page2(request, applicant_id):
    """他ユーザーの情報を閲覧できるページ"""
    s_id = applicant_id
    user = User.objects.get(username=s_id)
    # この方法しか今のとこ無理だけどusername重複した場合は？→重複しなかった(アカウント登録画面で弾かれた)
    profile = Profile.objects.get(user=user.id)
    # apply = Apply.objects.get(id=apply_id)
    context = {'profile':profile}

    return render(request, 'learning_logs/other_users_page2.html', context)


@login_required
def apply_entry(request, entry_id, user_id):
    """応募確認ページ"""
    entry = Entry.objects.get(id=entry_id)
    if request.method != 'POST':
        form = ApplyForm()
    
    else:
        #送信されたデータの処理
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            apply = form.save(commit=False)
            # apply = Apply(entry_id=entry, owner_id=entry.entry_owner, applicant_id=request.user)
            apply.entry_id = entry
            apply.owner_id = entry.entry_owner
            apply.applicant_id = request.user
            apply.save()
            context = {'entry_id':entry_id, 'user_id':user_id, 'entry':entry}
            return redirect('learning_logs:apply_entered', user_id, entry_id)

    context = {'form':form, 'entry_id':entry_id, 'user_id':user_id, 'entry':entry}
    return render(request, 'learning_logs/apply_entry.html',  context)
    #応募機能仮完成→応募最終確認のページ作成へ


@login_required
def recommend(request, profile_user):
    """応募確認ページ"""
    name = profile_user
    user = User.objects.get(username=name)
    profile = Profile.objects.get(user=user.id)
    if request.method != 'POST':
        form = RecommendForm()
    
    else:
        # if request.user != entry.
        #送信されたデータの処理
        form = RecommendForm(request.POST)
        if form.is_valid():
            recommend = form.save(commit=False)
            # recommend.owner_id = request.user
            recommend.user_id = user.id
            recommend.save()
            # context = {'entry_id':entry_id, 'user_id':user_id, 'entry':entry}
            return redirect('learning_logs:other_page', profile.user)

    context = {'form':form, 'profile':profile}
    return render(request, 'learning_logs/recommend.html',  context)

users/views.py
import re
from socketserver import DatagramRequestHandler
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """新しいユーザーを登録する"""
    if request.method != 'POST':
        # 空のユーザー登録フォームを表示する
        form = UserCreationForm()
    else:
        # 入力済みのフォームを処理する
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # ユーザーをログインさせてホームページにリダイレクトする
            login(request, new_user)
            return redirect('learning_logs:index')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/apply_entered.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block page_header %}
<h4>応募完了</h4>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/every_entry.css' %}">
{% endblock page_header %}


{% block content %}
<div class="center">
<h3>応募が完了しました</h3><br>
<p>登録されたメールアドレスに、記事作成者からメールが届きます。<br>それまでしばらくお待ちください。</p>

</div>
{% endblock content %}

learning_logs/templates/learning_logs/apply_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}


{% block page_header %}
<h4>応募準備</h4>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/new_entry.css' %}">
{% endblock page_header %}

{% block content %}

<div class="formtag">
<form action="{% url 'learning_logs:apply_entry' entry.id user.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <p>"{{ entry.title }}/{{ entry.entry_owner }}"　へ本当に応募してよろしいですか？</p>
    <button name='submit' type="submit" class="btn btn-primary">応募する</button>
{% comment %} <a class="btn btn-lg btn-primary" role="button" type= href="{% url 'learning_logs:apply_entered' entry.id user.id %}">応募する &raquo;</a> {% endcomment %}
</form>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html  lang="ja">
    <head>
        <meta charset="uff-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'learning_logs/base.css' %}">
        <title>RecruitCEO</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>
    <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
            RecruitCEO
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:entries' %}">
                    募集記事一覧
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                    職種から探す
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:users' %}">
                    ユーザーを 探す
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:new_entry' %}">
                    新規記事
                </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:my_page' user.id %}">
                    マイページ
                </a>
                </li>
                {% else %}
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">こんにちは "{{ user.username }}" さん</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">ログアウト</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">ユーザー登録</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">ログイン</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

    </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}


{% block page_header %}
<h4>記事を編集:</h4>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/new_entry.css' %}">
{% endblock page_header %}

{% block content %}


<div class="formtag">
    <a>関連トピックが見つからない方は<a href="{% url 'learning_logs:new_topic' %}">こちら</a></a>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        {% comment %} <button name="submit">記事を更新</button> {% endcomment %}
        <button name="submit" type="submit" class="btn btn-primary" >記事を更新</button>
    </form>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/every_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block page_header %}
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/text-align.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/every_entry.css' %}">

{% endblock page_header %}

{% block content %}

    <ul>
        <div class="center">
                {% if entry.image %}
                <div class="img-content">
                <img src="/{{entry.image}}" class="img-fluid"><br>
                </div>
                {% endif %}
                    <h3>{{entry.title}}</h3>
                    <h4>トピック：{{ entry.topic }}</h4>
                    <h5><a href="{% url 'learning_logs:other_page2' entry.entry_owner %}">オーナー：{{ entry.entry_owner }}</a></h5>
                    <div class="gray"><a>{{ entry.date_added }}</a></div>
                    <div class="border-top"></div>
                <p class="main_text">{{ entry.text | linebreaks | urlize}}</p>
                <br>
                <div class="border-top"></div>
                <div class="main_text">
                    <h3>募集要項</h3>
                    <br>
                <h4>応募資格：</h4><p>{{ entry.eligibility | linebreaks}}</p>
                <br>
                <h4>事業所住所：</h4><p>{{ entry.address }}</p>
                <br>
                <h4>選考方法：</h4><p>{{ entry.selection_method | linebreaks | urlize }}</p><br>
                <a class="btn btn-lg btn-primary" role="button" href="{% url 'learning_logs:apply_entry' entry.id user.id %}">応募する &raquo;</a>
                </div>
    </ul>

<h3>
</div>
    {% comment %} <a href="{% url 'learning_logs:new_topic' %}">新規トピックを追加</a></h3> {% endcomment %}


{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<!-- 親テンプレート指示(extends) -->

{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">あなたの後継者を探そう</h1>
    <p class="lead">会社の後継者がいないなら、<br>
                    募集記事を掲載して、次の経営者候補を探してみませんか。<br>
                    そして、キャリアがあっても職のないあなた。<br>
                    あなたの会社を探してみませんか。</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">登録する &raquo;</a>

</div>

{% endblock page_header %}
<!-- コンテンツ定義完了 -->

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}


{% block page_header %}
<h4>新しい記事を追加:</h4>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/new_entry.css' %}">
{% endblock page_header %}

{% block content %}

    {% comment %} <p><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p> {% endcomment %}
    <div class="formtag">
        <a>関連トピックが見つからない方は<a href="{% url 'learning_logs:new_topic' %}">こちら</a></a>
            <form action="{% url 'learning_logs:new_entry'%}" method='post' enctype='multipart/form-data'>
                {% comment %} 後でURL差し替える {% endcomment %}
                {% csrf_token %}
                {{ form.as_p }}
                <button name='submit' type="submit" class="btn btn-primary" >記事を追加</button>
            </form>
    </div>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block page_header %}
<h4>新規トピックを追加:</h4>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/new_entry.css' %}">
{% endblock page_header %}

{% block content %}
{% comment %} <p>新規トピックを追加:</P> {% endcomment %}

    <div class="formtag">
    <form action="{% url 'learning_logs:new_topic' %}" method='post'><br>
        <div class="input-group mb-3">
            {% csrf_token %}
            {% comment %} {{ form.as_p }} {% endcomment %}
            {{ form }}
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2" name="submit">トピックを追加</button>
          </div>
    </div>
        {% comment %} {% csrf_token %}
        {{ form.text }}
        <button name="submit">トピックを追加</button> {% endcomment %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block page_header %}
<h3>トピック一覧</h3>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/text-align.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/every_entry.css' %}">
{% endblock page_header %}

{% block content %}

<div class="center">
    <ul>
        {% for topic in topics %}
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3></li>
        {% empty %}
        <p>トピックはまだ作成されていません。</p>
        {% endfor %}
    </ul>
</div>
    {% comment %} <button type="button" class="btn btn-outline-secondary"><a href="{% url 'learning_logs:new_topic' %}">＋ 新規トピックを追加</a></button> {% endcomment %}


{% endblock content %}

learning_logs/templates/learning_logs/users.html
{% extends 'learning_logs/base.html' %}
{% load static %}

{% block page_header %}
<h3>ユーザー一覧</h3>
<link rel="stylesheet" type="text/css" href="{% static 'learning_logs/every_entry.css' %}">
{% endblock page_header %}

{% block content %}

<div class="center">
{% if form %}<!-- searchFormがあれば -->
    <form action="{% url 'learning_logs:users' %}" method="get"><!-- getメソッドでインデックス関数を呼び出す -->
        <div class="btn-group" role="group" aria-label="Basic example">
            {{ form }}<!-- views.pyから受け取ったsearchFormを表示 -->
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2" name="submit">検索</button>
            <button class="btn btn-outline-secondary" type="button" id="button-addon2" name="submit">
            <a href="{% url 'learning_logs:users' %}">クリア</a><!-- postメソッドでインデックス関数を呼び出す --></button>
        </div>
    </form><br>

{% endif %}


    {% for user in users %}


  <div class="card border-secondary mb-3">
    <a href="{% url 'learning_logs:other_page2' user.user %}" class="stretched-link" ></a>
    <div class="card-header">{{ user.user }}</div>
    <div class="card-body text-secondary">
      <h5 class="card-title">{{ user.family_name }}{{ user.first_name }}</h5>
      <p class="card-text">{{ user.career }}</p>
      <p class="card-text">{{ user.introduce | truncatechars:30 }}</p>
    </div>
  </div>

    {% endfor %}
</div>

{% endblock content %}